### ISSUE TITLE
Mobile api return 404

### ISSUE THREAD

**Issue by fatuuse** [claha/pyavanza#52]
API adress: https://www.avanza.se/_mobile/market
Http return 404. Avanza changed their API?

Se also: https://github.com/custom-components/sensor.avanza_stock/issues/145

**Comment by claha** [comment]
Fixed in 0.2.4 but my intentions are to release version 0.4.0 that uses the new api but looks more like version 0.3.x

**Comment by claha** [comment]
Released 0.4.0 that uses the new api
